### ISSUE TITLE
[Docs] Add Docker COPY from Example

### ISSUE THREAD

**Issue by yordis** [fboulnois/pg_uuidv7#31]
Hey there, I wonder if we could ["merge"](https://github.com/moby/moby/issues/3378#issuecomment-411824851) the `pg_uuidv7` image into the base image.

- Why would you do that?

I have other extension requirements aside from `pg_uuidv7`, and I am hoping that such a pattern becomes familiar enough so Extension Authors could provide a straightforward image to `COPY` from instead of relying on tools like `pgxn` or `pgxman`, or deal with "complex" (unfamiliar) installations steps and instead take advantage of Official Docker Image.

```dockerfile
FROM postgres:latest

COPY --from=ghcr.io/fboulnois/pg_uuidv7:1.5.0 /[help here] /[help here]
```

I appreciate any help you can provide.

**Comment by yordis** [comment]
Ideally, create a `ghcr.io/fboulnois/pg_uuidv7:1.5.0-extension` image so that it is safe to copy everything from it:

```dockerfile
FROM postgres:latest

COPY --from=ghcr.io/fboulnois/pg_uuidv7:1.5.0-extension /PGEXTENSION /
````

Where that tree under `/PGEXTENSION` has ONLY the files required to copy into my image

**Comment by heyztb** [comment]
Hey there, while I'm not the maintainer for this extension, I did see this and figured this could be done pretty easily. 

Here's an example I put together

```
FROM postgres:alpine3.18@sha256:354a818d8a1e94707704902edb8c4e98b0eb64de3ee0354c4d94b4e2905c63ee

RUN apk update && apk add curl \
    && cd $(mktemp -d) \
    && curl -LO "https://github.com/fboulnois/pg_uuidv7/releases/download/v1.5.0/pg_uuidv7.tar.gz" \
    && curl -LO "https://github.com/fboulnois/pg_uuidv7/releases/download/v1.5.0/SHA256SUMS" \
    && tar xf pg_uuidv7.tar.gz \
    && sha256sum -c SHA256SUMS \
    && if [ $? -ne 0 ]; then echo "Checksum verification failed" && exit 1; fi \
    && cp "$PG_MAJOR/pg_uuidv7.so" "$(pg_config --pkglibdir)" \
    && cp pg_uuidv7--1.5.sql pg_uuidv7.control "$(pg_config --sharedir)/extension"

RUN echo "CREATE EXTENSION pg_uuidv7;" > /docker-entrypoint-initdb.d/create_pg_uuidv7.sql
```

```
db=# select uuid_generate_v7();
           uuid_generate_v7           
--------------------------------------
 018e68a2-cab5-79d6-8f57-f7c0e7694dc4
(1 row)
```

I'm using this alongside Docker Compose, so I've got the environment variables that Postgres needs during setup defined there instead of in this Dockerfile. That looks like this:

```
services:
  db:
    build: 
      context: .
      dockerfile: pg-Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
```
